# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Circuit.create(
ref:'Primary',
category:'IPVPN',
speed:'100Mb',
carrier:'Eir',
carrierRef:'WES14',
site_id:2
)

Site.create(
name:'HQ',
address:'Leopardstown',
contact:'Tom',
phone:'123456',
email:'tom@mail.com',
customer_id:1
)
Site.create(
name:'Galway',
address:'Galway',
contact:'Paula',
phone:'87654',
email:'paula@mail.com',
customer_id:1
)
Site.create(
name:'Galway 2',
address:'Galway 2',
contact:'Paula',
phone:'87654',
email:'paula@mail.com',
customer_id:1
)
Site.create(
name:'Cork',
address:'Cork',
contact:'Janice',
phone:'7653763',
email:'janice@mail.com',
customer_id:1
)
Site.create(
name:'Belfast',
address:'Belfast',
contact:'Harry',
phone:'653764373',
email:'harry@mail.com',
customer_id:2
)
Circuit.create(
ref:'Primary',
category:'IPVPN',
speed:'100Mb',
carrier:'VM',
carrierRef:'VM3434',
site_id:1
)
Circuit.create(
ref:'Primary',
category:'IPVPN',
speed:'100Mb',
carrier:'VM',
carrierRef:'VM343476',
site_id:3
)
Circuit.create(
ref:'Primary',
category:'DIA',
speed:'10Mb',
carrier:'VM',
carrierRef:'VM445',
site_id:4
)
Circuit.create(
ref:'Primary',
category:'DIA',
speed:'50Mb',
carrier:'Eir',
carrierRef:'WES8887',
site_id:5
)
Circuit.create(
ref:'Primary',
category:'DIA',
speed:'50Mb',
carrier:'enet',
carrierRef:'EN647',
site_id:6
)
Circuit.create(
ref:'Back up',
category:'IPVPN',
speed:'70Mb',
carrier:'enet',
carrierRef:'EN33343',
site_id:6
)
Circuit.create(
ref:'Back up',
category:'IPVPN',
speed:'50Mb',
carrier:'enet',
carrierRef:'EN34536',
site_id:5
)
Circuit.create(
ref:'Back up',
category:'IPVPN',
speed:'50Mb',
carrier:'VM',
carrierRef:'VM87',
site_id:4
)
Circuit.create(
ref:'Back up',
category:'IPVPN',
speed:'70Mb',
carrier:'VM',
carrierRef:'VM23232',
site_id:3
)
Circuit.create(
ref:'Back up',
category:'IPVPN',
speed:'100Mb',
carrier:'Host',
carrierRef:'HVF678',
site_id:2
)
Circuit.create(
ref:'Primary',
category:'IPVPN',
speed:'100Mb',
carrier:'Host',
carrierRef:'HVF9888',
site_id:1
)
